import type { DestinationCatalogEntry } from "@/lib/types";

export const destinationCatalog: DestinationCatalogEntry[] = [
  {
    id: "kyoto-japan",
    name: "Kyoto",
    country: "Japan",
    summary: "A calm cultural city with temples, tea houses, and excellent seasonal food.",
    budgetBand: "medium",
    climate: ["mild", "cold"],
    interests: ["culture", "history", "food"],
    bestMonths: ["March", "April", "October", "November"],
    tripStyles: ["solo", "couple", "friends", "family"],
  },
  {
    id: "chiang-mai-thailand",
    name: "Chiang Mai",
    country: "Thailand",
    summary: "A relaxed northern Thai hub for food, temples, and easy-going nature escapes.",
    budgetBand: "low",
    climate: ["warm", "mild"],
    interests: ["food", "culture", "nature"],
    bestMonths: ["November", "December", "January", "February"],
    tripStyles: ["solo", "couple", "friends"],
  },
  {
    id: "lisbon-portugal",
    name: "Lisbon",
    country: "Portugal",
    summary: "A sunny coastal capital with trams, tiled streets, seafood, and nearby beaches.",
    budgetBand: "medium",
    climate: ["warm", "mild"],
    interests: ["food", "history", "beach"],
    bestMonths: ["April", "May", "September", "October"],
    tripStyles: ["solo", "couple", "friends", "family"],
  },
  {
    id: "queenstown-new-zealand",
    name: "Queenstown",
    country: "New Zealand",
    summary: "A dramatic alpine base for outdoor adventure and scenic drives.",
    budgetBand: "high",
    climate: ["mild", "cold"],
    interests: ["nature", "adventure"],
    bestMonths: ["December", "January", "February", "March"],
    tripStyles: ["solo", "couple", "friends"],
  },
  {
    id: "seoul-south-korea",
    name: "Seoul",
    country: "South Korea",
    summary: "A fast-moving city break mixing food alleys, shopping districts, and palaces.",
    budgetBand: "medium",
    climate: ["mild", "cold"],
    interests: ["food", "shopping", "culture", "nightlife"],
    bestMonths: ["April", "May", "September", "October"],
    tripStyles: ["solo", "couple", "friends"],
  },
  {
    id: "bali-indonesia",
    name: "Bali",
    country: "Indonesia",
    summary: "A tropical island for beach days, temples, cafes, and villa-style stays.",
    budgetBand: "medium",
    climate: ["warm"],
    interests: ["beach", "nature", "culture", "food"],
    bestMonths: ["April", "May", "June", "September"],
    tripStyles: ["couple", "friends", "family"],
  },
  {
    id: "chengdu-china",
    name: "Chengdu",
    country: "China",
    summary: "A laid-back city known for Sichuan food, tea houses, and nearby nature trips.",
    budgetBand: "low",
    climate: ["mild"],
    interests: ["food", "culture", "nature"],
    bestMonths: ["March", "April", "October", "November"],
    tripStyles: ["solo", "couple", "friends", "family"],
  },
  {
    id: "vancouver-canada",
    name: "Vancouver",
    country: "Canada",
    summary: "A polished coastal city where urban comfort meets mountain and sea access.",
    budgetBand: "high",
    climate: ["mild", "cold"],
    interests: ["nature", "food", "shopping"],
    bestMonths: ["June", "July", "August", "September"],
    tripStyles: ["solo", "couple", "family"],
  },
  {
    id: "istanbul-turkiye",
    name: "Istanbul",
    country: "Turkiye",
    summary: "A layered cross-continental city full of markets, mosques, and rich history.",
    budgetBand: "medium",
    climate: ["mild", "warm"],
    interests: ["history", "culture", "food", "shopping"],
    bestMonths: ["April", "May", "September", "October"],
    tripStyles: ["solo", "couple", "friends", "family"],
  },
  {
    id: "da-nang-vietnam",
    name: "Da Nang",
    country: "Vietnam",
    summary: "A beach-friendly city with good food access and easy day trips to Hoi An and Hue.",
    budgetBand: "low",
    climate: ["warm"],
    interests: ["beach", "food", "culture"],
    bestMonths: ["February", "March", "April", "May"],
    tripStyles: ["couple", "friends", "family"],
  },
  {
    id: "barcelona-spain",
    name: "Barcelona",
    country: "Spain",
    summary: "A vivid Mediterranean city blending architecture, food, beaches, and nightlife.",
    budgetBand: "medium",
    climate: ["warm", "mild"],
    interests: ["food", "beach", "culture", "nightlife"],
    bestMonths: ["May", "June", "September", "October"],
    tripStyles: ["solo", "couple", "friends", "family"],
  },
  {
    id: "sapporo-japan",
    name: "Sapporo",
    country: "Japan",
    summary: "A colder-weather destination with winter fun, comforting food, and easy nature access.",
    budgetBand: "medium",
    climate: ["cold"],
    interests: ["food", "nature", "adventure"],
    bestMonths: ["January", "February", "December"],
    tripStyles: ["solo", "couple", "friends", "family"],
  },
];
